remote_theme: pages-themes/slate@v0.2.0
exclude: [README.md]
# This prevents Jekyll from crashing on Obsidian-specific syntax
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false


# _config.yml

# This tells Jekyll to ignore these specific files and folders
exclude:
  - 90-Template/
  - .obsidian/
  - .trash/
  - .smart-env/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/